include: package:flutter_lints/flutter.yaml

analyzer:
  exclude:
    - build/**
    - "**/*.g.dart"
    - lib/core/l10n/generated/**
    - android/**
    - ios/**
  language:
    strict-casts: true
    strict-raw-types: true

linter:
  rules:
    - prefer_single_quotes
    - prefer_const_constructors
    - prefer_final_locals
    - always_declare_return_types
    - avoid_dynamic_calls
    - unawaited_futures
