import 'dart:convert';

/// A check-in made on a home-screen widget while the app wasn't running.
/// Widgets append these to a shared queue; the app merges them into the
/// database (as `source = widget` events) on launch / resume.
class PendingWidgetEvent {
  const PendingWidgetEvent({
    required this.id,
    required this.dailyTaskId,
    required this.date,
    required this.occurredAt,
    this.action = actionAdvance,
  });

  static const String actionAdvance = 'advance';

  /// Unique id generated by the widget (used to remove merged entries).
  final String id;
  final int dailyTaskId;

  /// `yyyy-MM-dd` of the task the widget showed.
  final String date;
  final DateTime occurredAt;
  final String action;

  Map<String, Object?> toJson() => {
    'id': id,
    'dailyTaskId': dailyTaskId,
    'date': date,
    'occurredAt': occurredAt.toUtc().toIso8601String(),
    'action': action,
  };

  factory PendingWidgetEvent.fromJson(Map<String, Object?> j) =>
      PendingWidgetEvent(
        id: j['id']! as String,
        dailyTaskId: (j['dailyTaskId']! as num).toInt(),
        date: j['date']! as String,
        occurredAt: DateTime.parse(j['occurredAt']! as String).toLocal(),
        action: j['action'] as String? ?? actionAdvance,
      );

  /// Decodes a queue; malformed entries are skipped rather than blocking the
  /// whole queue forever.
  static List<PendingWidgetEvent> decodeQueue(String? raw) {
    if (raw == null || raw.isEmpty) return const [];
    final Object? list;
    try {
      list = jsonDecode(raw);
    } on FormatException {
      return const [];
    }
    if (list is! List<Object?>) return const [];
    final out = <PendingWidgetEvent>[];
    for (final item in list) {
      try {
        out.add(PendingWidgetEvent.fromJson(item! as Map<String, Object?>));
      } catch (_) {
        // Skip malformed entry.
      }
    }
    return out;
  }

  static String encodeQueue(List<PendingWidgetEvent> events) =>
      jsonEncode(events.map((e) => e.toJson()).toList());
}
